matrix:
  include:
    - language: java
      jdk:
        - oraclejdk11
      before_install:
        - javac -version
      script:
        - cd Java/src
        - javac -cp "../../lib/*" Signs.java Server.java
        - cd ../test
        - javac -cp "../../lib/*:../src" SignsTest.java ServerTest.java
        - java -javaagent:../../lib/jacocoagent.jar=destfile=../../jacoco.exec -cp "../lib/*:../src:." org.junit.runner.JUnitCore SignsTest ServerTest
        - java -jar "../../lib/jacococli.jar" report ../jacoco.exec --classfiles . --sourcefiles . --xml .. --name JaCoCo
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: node_js
      node_js:
        - node
        - lts/*
      cache:
        directories:
          - ~/.npm
      before_script:
        - cd skilt-info
        - npm install -g npm@latest
      script:
        - npm ci
        - npx jest --ci


