matrix:
  include:
    - language: java
      jdk:
        - oraclejdk11
      before_install:
        - javac -version
      script:
        - cd Java/src
        - javac -cp "../../lib/*" HttpRoadSignDao.java Server.java WGS2UTM.java CreateUriUtil.java
        - cd ../test
        - javac -cp "../../lib/*:../src" HttpRoadSignDaoTest.java ServerTest.java
        - java -javaagent:../../lib/jacocoagent.jar=destfile=../jacoco.exec -cp "../../lib/*:../src:.:../resources" org.junit.runner.JUnitCore HttpRoadSignDaoTest ServerTest
        - java -jar "../../lib/jacococli.jar" report ../jacoco.exec --classfiles . --sourcefiles . --xml ../../jacoco*.xml
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: node_js
      node_js:
        - node
        - lts/*
      cache:
        directories:
          - ~/.npm
      before_script:
        - cd skilt-info
        - npm install -g npm@latest
      script:
        - npm ci
        - npx jest --ci